

# change user and passwd if you use it

all: 
	python3 test.py

debug:
	python3 debug.py

tcmd:
	python3 tcmd.py

infinite:
	python3 infinite.py

runCommand:
	python3 runCommand.py list
	python3 runCommand.py list simple
